// src/types.ts
// Import the Database type generated by Supabase CLI
// Adjust path as needed based on your project structure
import { type Database } from "./db/database.types";

// --- Shared Utility Type ---
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

// --- Database Derived Types ---
// Alias types derived from the Supabase generated Database type for better readability
export type MeetingSummaryDbRow = Database["public"]["Tables"]["meeting_summaries"]["Row"];
export type MeetingSummaryDbInsert = Database["public"]["Tables"]["meeting_summaries"]["Insert"];
export type MeetingSummaryDbUpdate = Database["public"]["Tables"]["meeting_summaries"]["Update"];

// --- API Request DTOs ---

/**
 * DTO representing the request body for POST /api/summaries.
 * Matches the API specification for input data.
 * NOTE: Based on current DB schema and migrations, 'title' is NOT included here
 * as it seems to be generated by the backend or not provided via this specific DTO.
 */
export interface CreateSummaryRequestDTO {
  file_name?: string | null; // Optional in API, can be null or undefined
  transcription: string; // Required
  summary: string; // Required, max 500 characters in API spec (DB column is TEXT/string, Zod enforces length)
  llm_generated: boolean; // Required
  notes?: string | null; // Optional (API spec says 'string', can be empty string or null)
}

/**
 * DTO representing the request body for PUT /api/summaries/{id}.
 * Often similar to Create but might have different optionality or exclude fields.
 * Assuming it can update transcription, summary, file_name, notes, llm_generated.
 * Title is still assumed to be managed by backend or not updatable via this endpoint DTO.
 */
export interface UpdateSummaryRequestDTO {
  file_name?: string | null; // Optional
  transcription?: string; // Optional on update, but required if changing
  summary?: string; // Optional on update, but required if changing
  llm_generated?: boolean; // Optional
  notes?: string | null; // Optional
}

// --- API Response DTOs ---

/**
 * DTO representing the response body for successful POST /api/summaries (201 Created).
 * Based on the full DB row, mapping modified_at to updated_at, including 'title'.
 */
export type CreateSummaryResponseDTO = Omit<MeetingSummaryDbRow, "modified_at"> & {
  updated_at: MeetingSummaryDbRow["modified_at"]; // API uses 'updated_at'
  // MeetingSummaryDbRow already includes id, user_id, file_name, created_at, transcription, summary, llm_generated, notes, title
};

/**
 * DTO representing a single entry in the list response for GET /api/summaries.
 * Contains basic information for the list view, including 'title' and mapped 'updated_at'.
 * Matches the columns selected in the GET handler's service.
 */
export type MeetingSummaryListEntryDto = Pick<MeetingSummaryDbRow, "id" | "title" | "file_name" | "created_at"> & {
  updated_at: MeetingSummaryDbRow["modified_at"]; // Map DB 'modified_at' to API 'updated_at'
};

/**
 * DTO representing the full list response for GET /api/summaries.
 */
export type MeetingSummaryListDto = MeetingSummaryListEntryDto[];

/**
 * DTO representing the detailed information for a single summary (GET /api/summaries/{id}).
 * Includes all fields from the DB row except user_id, with mapped 'updated_at'.
 */
export type MeetingSummaryDetailsDto = Omit<
  MeetingSummaryDbRow,
  "user_id" | "modified_at" // user_id is omitted, modified_at is mapped
> & {
  updated_at: MeetingSummaryDbRow["modified_at"]; // API uses 'updated_at'
};

// --- Command/Service Layer Internal Types ---
// These types are used within the backend logic (handlers, services, repositories)
// Included here for completeness as they were in the provided types,
// but primarily relevant for backend implementation, not frontend views themselves.

/**
 * Type representing the structure of data inserted into the 'meeting_summaries' table.
 * Alias for the Supabase generated Insert type for this table.
 */
export type MeetingSummaryInsertData = MeetingSummaryDbInsert;

/**
 * Type representing the shape of a FULL row as returned by a SELECT query
 * like `select()`.
 * Alias for the Supabase generated Row type for this table.
 */
export type MeetingSummaryFullRow = MeetingSummaryDbRow;

/**
 * Type representing a subset of columns selected by the GET /api/summaries handler.
 * Explicitly defined to match the `.select()` call in SummaryService.
 */
export type MeetingSummarySelectedColumns = Pick<
  MeetingSummaryDbRow,
  "id" | "title" | "file_name" | "created_at" | "modified_at"
>;

/**
 * Command Model for query parameters for the list summaries endpoint (GET /api/summaries).
 * Represents the parsed and validated query parameters.
 */
export interface ListSummariesCommand {
  sort_by: "created_at" | "updated_at"; // API terms
  sort_order: "asc" | "desc";
  from_dt?: string; // ISO 8601 string (date only YYYY-MM-DD format expected by HTML input type="date")
  to_dt?: string; // ISO 8601 string (date only YYYY-MM-DD format expected by HTML input type="date")
}

/**
 * Type for parameters passed to the SummaryService's list method.
 * Uses Date objects for date range and DB column names for sorting.
 */
export interface ListSummariesServiceParams {
  userId: string;
  dateRange: { from?: Date; to?: Date };
  sortParams: {
    by: "created_at" | "modified_at"; // Service internal uses DB column names
    order: "asc" | "desc";
  };
}

// --- Other Command Models ---

/**
 * Command Model for the Generate Summary action (POST /api/generate-summary).
 */
export interface GenerateSummaryCommand {
  transcription: string; // The transcription text to summarize
}

/**
 * DTO representing the response from the Generate Summary action.
 */
export interface GenerateSummaryResponseDto {
  summary: string; // The generated summary text
}

// Note: Endpoint DELETE /api/summaries/{id} returns 204 No Content.
// Note: Endpoint PUT /api/summaries/{id} would likely need an UpdateMeetingSummaryCommand
// and an UpdateMeetingSummaryResponseDto. UpdateSummaryRequestDTO is defined above for frontend use.
